MODELAGEM CONCEITUAL

CRIAR TABELA CLIENTE
IDCLIENTE INTEIRO NÃO NULO AUTO_INCREMENT
NOME STRING(30) NÃO NULO,
SEXO ('M','F') NÃO NULO,
EMAIL STRING(30),
CPF STRING(15) NÃO NULO ÚNICO


CRIAR TABELA ENDERECO
IDENDERECO INTEIRO NÃO NULO AUTO_INCREMENT
RUA STRING(30) NÃO NULO,
BAIRRO STRING(30) NÃO NULO,
CIDADE STRING(30) NÃO NULO,
ESTADO CARACTER(2)
CHAVE ESTRAGEIRA


CRIAR TABELA TELEFONE
IDTELEFONE INTEIRO NÃO NULO AUTO_INCREMENT
TIPO ENUMERADO('CEL','RES','COM'),
NUMERO STRING(15),
CHAVE ESTRAGEIRA
