CRIANDO BANCO DE DADOS 'DBCOMERCIO'

CREATE DATABASE DBCOMERCIO;


***********************************************************


INSERINDO DADOS PARA TABELA 'CLIENTE'


INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','99787-3');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOS@TERA.COM','94567-2');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@GLOBO.COM','67889-0');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','98433-7');
INSERT INTO CLIENTE VALUES(NULL,'CLRA','F',NULL,'99876-2');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','F','JOAO@TERRA.COM','77456-7');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M',NULL,'75667-1');
INSERT INTO CLIENTE VALUES(NULL,'JOAO','M',NULL,'88667-1');


***************************************************************************

INSERINDO DADOS PARA TABELA 'ENDERECO'


INSERT INTO ENDERECO VALUES (NULL,'RUA A','CENTRO','BELO HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA C','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA B','ESTACIO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','BELO HORIZONTE','MG',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','FLAMENTO','RIO DE JANEIRO','RJ',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA Z','CRUZEIRO','BELO HORIZONTE','MG',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA X','CENTRO','NITEROI','RJ',6);

***************************************************************************

INSERINDO DADOS PARA TABELA 'TELEFONE'

INSERT INTO TELEFONE VALUES(NULL,'CEL','98334565',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33495678',3);
INSERT INTO TELEFONE VALUES(NULL,'RES','99878654',2);
INSERT INTO TELEFONE VALUES(NULL,'COM','12343456',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','76865543',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','54567655',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','98334555',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','98334598',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','98444565',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','98774565',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','45678999',6);
INSERT INTO TELEFONE VALUES(NULL,'RES','90889045',6);





